// 将 vitest coverage 生成的 istanbul HTML 报告中文化
// 用法：node scripts/coverage-zh.cjs（通常接在 test:coverage 之后）
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..", "coverage");

// [英文原文, 中文译文] —— 顺序敏感，All files 需先于前缀替换之前/之后均可
const replacements = [
  ['<html lang="en">', '<html lang="zh-CN">'],
  ["All files", "全部文件"],
  ["Code coverage report for ", "覆盖率报告："],
  [">Statements<", ">语句<"],
  [">Branches<", ">分支<"],
  [">Functions<", ">函数<"],
  [">Lines<", ">行<"],
  ['class="file">File</th>', 'class="file">文件</th>'],
  ["Filter:", "过滤："],
  [
    "Press <em>n</em> or <em>j</em> to go to the next uncovered block, <em>b</em>, <em>p</em> or <em>k</em> for the previous block.",
    "按 <em>n</em> 或 <em>j</em> 跳到下一个未覆盖块，<em>b</em>、<em>p</em> 或 <em>k</em> 跳到上一个。",
  ],
  ["Uncovered Line #s", "未覆盖行号"],
  ["Generated by istanbul", "由 istanbul 生成"],
  // 文件详情页常见
  ["No coverage information", "无覆盖率信息"],
];

function walk(dir) {
  let count = 0;
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name);
    if (fs.statSync(p).isDirectory()) {
      count += walk(p);
    } else if (name.endsWith(".html")) {
      let s = fs.readFileSync(p, "utf8");
      let changed = false;
      for (const [from, to] of replacements) {
        if (s.includes(from)) {
          s = s.split(from).join(to);
          changed = true;
        }
      }
      if (changed) {
        fs.writeFileSync(p, s, "utf8");
        count++;
      }
    }
  }
  return count;
}

if (fs.existsSync(root)) {
  const n = walk(root);
  console.log(`覆盖率报告已中文化（${n} 个 HTML 文件）`);
} else {
  console.log("coverage 目录不存在，跳过中文化");
}
